.github/workflows/lint-test.yaml
.github/workflows/release.yaml
ct.yaml

The purpose of this PR is to create the necessary github actions framework to properly lint & test new & changed charts as they arrive via pull requests.  It will also properly 'release' charts merged to the master branch in the form of a repo 'release' and publishing of the `index.yml` file on the branch publishing the github pages.
This will also require the repo maintainer to:
* enable the github pages feature in the [settings](https://github.com/nextcloud/helm/settings)
* create a github pages branch (ideally named `gh_pages`) if it doesn't already exist

Adding github actions framework for charts

---

README.md
charts/nextcloud/.helmignore
charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/requirements.lock
charts/nextcloud/requirements.yaml
charts/nextcloud/templates/NOTES.txt
charts/nextcloud/templates/_helpers.tpl
charts/nextcloud/templates/config.yaml
charts/nextcloud/templates/cronjob.yaml
charts/nextcloud/templates/db-secret.yaml
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/templates/hpa.yaml
charts/nextcloud/templates/ingress.yaml
charts/nextcloud/templates/metrics-deployment.yaml
charts/nextcloud/templates/metrics-service.yaml
charts/nextcloud/templates/nextcloud-pvc.yaml
charts/nextcloud/templates/nginx-config.yaml
charts/nextcloud/templates/php-config.yaml
charts/nextcloud/templates/secrets.yaml
charts/nextcloud/templates/service.yaml
charts/nextcloud/values-mariadb.yaml
charts/nextcloud/values.yaml
ct.yaml

This is an import of the nextcloud chart with not material changes,
except for necessary changes from `stable/nextcloud` to the new helm
repo location of `nextcloud/helm` and associated github pages URL.
This also bumps the chart version to 2.0.0 in order to properly sort
this chart ahead of the (soon to be deprecated) stable/nextcloud chart.
Will wait to make this a real PR until #1 is merged.

Imports nextcloud helm chart from helm/stable

---

charts/nextcloud/Chart.yaml

There have been issues with misnamed 'gh pages' branch causing the chart releaser action to not properly complete. Bumping an end-to-end workflow of this chart to ensure that it all works as expected.

bump chart to validate actions

---

charts/nextcloud/Chart.yaml
charts/nextcloud/requirements.lock
charts/nextcloud/requirements.yaml
charts/nextcloud/values-mariadb.yaml
charts/nextcloud/values.yaml
ct.yaml

Works fine with mariadb. I haven't been able to test postgres or redis.
Signed-off-by: Ryan Holt <ryan@ryanholt.net>

[nextcloud] initial move to bitnami dependent charts and add postgres

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/metrics-deployment.yaml

Found this while enabling metric scraping on Rancher as this will otherwise also match the nextcloud deployment

Fix matchLabels to include metrics

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/cronjob.yaml
charts/nextcloud/values.yaml

- Upgrading app to latest 19.0.3
- Upgrading dependencies versions
- Cron to run every 5 minutes as specified in the [Nextcloud docs](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#background-jobs)
- Partially revert  #17 as there seem to be an issue with `trusted_domains` when trying to call `cron.php` without ingress
```
root@nextcloud-69c99f6d76-x45qc:/var/www/html# curl -I --fail -L http://nextcloud:8080/cron.php
curl: (22) The requested URL returned error: 400 Bad Request
```

Upgrade to latest version and fix cron

---

charts/nextcloud/Chart.yaml

I use [Velero](https://www.velero.io) to backup my database. The `pg_dump` & `pg_restore` combination I use requires a working user `postgres`. There is a bug in 9.7.2 and few version earlier, that prevent to set a password to `postgres` user.
It had been fixed in latest release https://github.com/bitnami/charts/pull/4123
This uprgade to latest stable PostgreSQL

Bump PostgreSQL to 9.8.9

---

.github/workflows/release.yaml
charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

The nextcloud deployment needs the ENV variable `REDIS_HOST_PASSWORD` set in order for authenticated redis to not have issues.  This should fix #29
See https://github.com/nextcloud/docker/pull/1232 for additional details

Set redis default password and ENV REDIS_HOST_PASSWORD

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/templates/secrets.yaml
charts/nextcloud/values.yaml

Introducing options nested under `nextcloud.existingSecret` to allow for a deployment that does not contain the secret and instead uses an existing secret.
Differences between `nextcloud/helm@master` and `michel-zimmer/helm@custom-secret` for `helm template .`:
_(no differences)_
```diff
diff --git charts/nextcloud/values.yaml charts/nextcloud/values.yaml
index cb3e14e..de5ae1f 100644
--- charts/nextcloud/values.yaml
+++ charts/nextcloud/values.yaml
@@ -66,10 +66,10 @@ nextcloud:
password: changeme
existingSecret:
-    enabled: false
-    # secretName: nameofsecret
-    # usernameKey: username
-    # passwordKey: password
+    enabled: true
+    secretName: my-secret-name
+    usernameKey: my-username-key
+    passwordKey: my-password-key
update: 0
datadir: /var/www/html/data
tableprefix: …
```

Add option for a custom secret

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

- When using nginx + nextcloud fpm image, `phpConfigs` are now mounted to /usr/local/etc/php-fpm.d instead of /usr/local/etc/php/conf.d

fixes nextcloud/helm#70 saving phpConfigs files to the right directory when using fpm

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml

This is to fix #60. I'm running this fork in prod now. a similar initcontainer could be added for postgress in the same way. More of an idea than anything, if there's anything you want me to change, or you want to take this and improve it to fit your needs that's fine.

Added initContainer to fix mariadb initial connection failing

---

charts/nextcloud/README.md

Improve the documentation for `externalDatabase.host`
Closes nextcloud#36

Add format of externalDatabase.host in docs (nextcloud#36)

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/service.yaml

The selector in `service.yaml` accidentally matches not only to the nextcloud pods, but also on cron and metrics:
```
kubectl get pods -l app.kubernetes.io/name=nextcloud
NAME                                 READY   STATUS      RESTARTS   AGE
nextcloud-65d4c48fd9-nxv7d           1/1     Running     0          12m
nextcloud-cron-1613603100-rf6cw      0/1     Completed   0          4m6s
nextcloud-metrics-6fc8bc88b5-86gpx   1/1     Running     0          12m
```
Adding the `component` label to the selector fixes this:
```
kubectl get pods -l app.kubernetes.io/name=nextcloud,app.kubernetes.io/component=app
NAME                         READY   STATUS    RESTARTS   AGE
nextcloud-65d4c48fd9-nxv7d   1/1     Running   0          13m
```

Fix selector

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml

Adds logic to use either credentials directly provided via helm chart or secrets referenced by in a k8s-secret for mariadb-isalive init pod.
Fixes #80 
I hope none.
- fixes #80

Use external secrets for mariadb-isalive if available.

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/config.yaml
charts/nextcloud/templates/deployment.yaml

* Adds an `initContainer` which uses `pg_isready` to postpone installation attempts
* Makes proper use of redis passwords, including `redis.existingSecret` from the dependent chart
* Better integration with redis and postgresql dependencies
- fixes #42

redis / postgresql improvements

---

charts/nextcloud/Chart.yaml
charts/nextcloud/values.yaml

Even with an empty password, nextcloud tries to AUTH with redis-6, which results in mysterious 303 when trying to log in
Redis works with the default config
- fixes #66 
This is what happens if the password is not set, but auth is disabled on redis side. Deleting the line
```
'password' => getenv('REDIS_HOST_PASSWORD'),
```
in redis.config.php doesn't help

Fix default redis config

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/metrics-deployment.yaml

Currently, the metrics refer only to default secret name. This cause the metric pod cannot find the secret reference, if you use the different chart value of `.nextcloud.existingSecret.secretName`.

Fix metrics secretKeyRef

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/_helpers.tpl
charts/nextcloud/templates/ingress.yaml

Renders the ingress resource according to newest supported apiVersion
networking.k8s.io/v1beta1 is going away soon. This also lays the groundwork for supporting High Performance Back-end in NC21
- fixes #

render ingress according to supported apiVersion

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/cronjob.yaml

Fixes YAML parse error on nextcloud/templates/cronjob.yaml when setting tolerations
Removes a `:` causing the following error when using `tolerations` in values.
Full error :
```
Error: UPGRADE FAILED: YAML parse error on nextcloud/templates/cronjob.yaml: error converting YAML to JSON: yaml: line 45: mapping values are not allowed in this context
```
Makes `tolerations` usable. 
None
None

fix: remove trailing colon in cronjob.yaml

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml

mariadb-isalive and postgresql-isready init containers now take their image name and tag from the postgres and mariadb sub charts.
you can now use this chart on a raspberrypi if you set the db images to the default (postgres:version)
also disabled the startupProbe if the chart is used with nginx configuration (as with the other probes)
- fixes #99 
- fixes #94 
- fixes #61

change initcontainers image and tag to follow subchart, disable startupProbe with nginx

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml

There is an inconsistency in the deployment.yaml now when specifying a redis password via secret. 
The template checks for `.Values.redis.existingSecretPasswordKey` to exist and then uses `.Values.redis.existingSecretKey` as the value instead. Looking at the Bitnami Redis chart specified in the dependencies, `existingSecretPasswordKey` is the correct name.
```
{{- if and .Values.redis.existingSecret .Values.redis.existingSecretPasswordKey }}
- name: REDIS_HOST_PASSWORD
valueFrom:
secretKeyRef:
name: {{ .Values.redis.existingSecret }}
key: {{ .Values.redis.existingSecretKey }} <--- does not match above
{{- else }}
```
Fixes a minor bug.
None. Since the user must be specifying `.Values.redis.existingSecretPasswordKey` today to get this to work, even if a workaround is in place (specifying …

Fix redis password secret key ref

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/templates/rbac.yaml
charts/nextcloud/templates/serviceaccount.yaml
charts/nextcloud/values.yaml

Gives you the possibility to create a service account for the deployment and RBAC to bind it to the priviledged PSP.
If you want to deploy this to a cluster that has PSP enabled, this makes it possible
Since it's an opt-in option this shouldn't affect any running or new deployments as long as you don't activate it.
Until #9 is closed, this is one way of getting the deployment up and running on clusters with PSP enabled

Added possibility to use priviledged PSP

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/cronjob.yaml

When pod security policies (PSP) are used, then the securityContext typically has e.g. a "runAsUser" attribute and a (non-default) service account. The cronjob uses the same security context as the regular deployment, so it should also use the same service account. With PSP enabled, a pod created with the "wrong" service account will not be able to start.
The current chart works with PSP (when security context and service account are set correctly). But when you enable the cronjob, it will not start - this is fixed here.
Cronjob pod has more permissions than it needs. But this is already the case, it starts "curl" as root by default, which is just not needed. Fixing this would be a breaking change and should be considered in a separate PR.
- PSP support: …

Use service account name also for cronjob

---

charts/nextcloud/Chart.yaml
charts/nextcloud/values.yaml

NC 19 is now out of support, update the default image to 20.0.11

Update nextcloud image to 20.0.11

---

.gitignore
charts/nextcloud/Chart.lock
charts/nextcloud/Chart.yaml

This change updates chart dependencies to the next non-breaking release.
It removes the Chart.lock from gitignore, since it's common to commit
this to repositories.
Probably less vulnerabilities in dependencies as they are still pretty outdated.

Update chart dependencies

---

.github/dependabot.yml

Adds Dependabot updates for GitHub Actions.
See: https://github.com/nextcloud/.github/blob/master/.github/dependabot.yml
Example: https://github.com/splitt3r/helm/pull/2
After merging this you will be able to trigger manual checks at https://github.com/nextcloud/helm/network/updates

Add Dependabot configuration from template repo

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/metrics-deployment.yaml

The exporter deployment incorrectly references the usernameKey instead of the passwordKey when using an existing secret.

Fix password key reference for existing secret

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/templates/rbac.yaml

Duplicate `serviceAccountName` key makes it impossible to use `kubectl kustomize` as a helm post-renderer hook.
This is because two templated YAMLs are not valid, so that `kustomize` cannot unmarshal them into kubernetes Go structs.
The duplicate key was removed from deployment spec.
Also, the namespace reference ` .Release.Namespace` was fixed in `rbac.yaml` because it is case sensitive.
IMHO, it might be a good idea to test validity of the rendered YAMLs in [the lint and/or release pipleline](https://github.com/nextcloud/helm/tree/master/.github/workflows). HDYT?
```bash
kubectl version
cd $pathToGitRepo
git checkout fix-deployment
mkdir kustomize
cat <<'EOF' > ./kustomize/kustomize.sh
#!/bin/bash
cat <&0 > "$(dirname $0)/all.yaml"
kubectl kustomize ./kustomize && rm "$(dirname …
```

fix duplicate key and wrong var name in templates

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/ingress.yaml
charts/nextcloud/values.yaml

Ability to configure for use with a GKE Ingress (on Google Cloud Platform). Before, this was not possible (see #158).
These values can be specified to make Nextcloud work on GKE (with a GKE Ingress):
```yaml
ingress:
enabled: true
annotations:
[...]
kubernetes.io/ingress.class: gce
[...]
path: /*
pathType: ImplementationSpecific
```
None. Other users don't have to change anything. Their setup is unaffected by this change.
- fixes #158

GKE ingress

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/templates/nextcloud-data-pvc.yaml
charts/nextcloud/values.yaml

implements partial #110.
We add the possibility to move data directory in a different PVC by setting a config flag.
This is DISABLED by default
In order to profit from different storage classes (e.g. high speed SSD and slow HDD) and special limits on the data.
If enabled creating a second PVC needs a few more ressources.
We might have problems if we want to delete this feature in the future with backwards compability.
no known

add posibility to have data on a second pvc that can have independent limits, storage class from main pvc

---

charts/nextcloud/README.md

Took me quite a while to figure out that Helm >=3.7.0 is necessary for this chart since #152. <br>
In my case for example ArgoCD uses Helm v3.6.0 and therefore could not render the templates if MariaDB is enabled.
May save the time of other people
Don't see any, only a readme addition

Add Helm version requirement to readme

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/_helpers.tpl

Fix typo for Ingress version to use
Allows chart to be used with `ingress.enabled=true` above v1.19
Untested on versions below v1.22
nil
nil

Use networking.k8s.io/v1 Ingress above k8s v1.19

---

charts/nextcloud/README.md

Added documentation on how to preserve source IP
Preserving source IP is important when having a deployment with Kubernetes when nextcloud is behind proxies and ingresses. 
This might only address baremetal deployment and not managed k8s clusters.
- fixes #

docs: Preserving source IP

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/metrics-deployment.yaml
charts/nextcloud/values.yaml

This PR foxes two issues of the metrics exporter implementation.
1. The current image is not v0.5.0, instead it is 0.5.0
2. The Environment variable for the token was renamed by the upstream project.
Metrics exporter will work again

fix nextcloud metrics

---

charts/nextcloud/Chart.lock
charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

nextcloud 23.0.2 -> 23.0.3
nextcloud-exporter 0.5.0 -> 0.5.1
postgresql 10.16.2 -> 11.1.17
mariadb 9.8.1 -> 10.4.5
redis 15.7.6 -> 16.8.4
@tvories

Bump nextcloud, dependencies and nextcloud-exporter

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/db-secret.yaml
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

The change fixes use of kubernetes-based PostgreSQL installed by `postgresql` subchart.
Before the patch PostgreSQL instance was created but not used by NextCloud (config was still using SQLite).
The structure of values in NectCloud's chart for `postgresql` subchart was different from one in `postgresql` chart itself which caused incorrect user and database creation.
Now if `postgresql.enabled` is set to `true` with all other values kept default, the instance of PostgreSQL is created in kubernetes cluster and used by NextCloud instance being installed.
Not found.
#15 or #168 or #226 (probably)
None

Fixed use of k8s-based postgresql

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml

The mariadb-isalive initContainer is missing its registry parameter. It can only work with images pulled from docker.
I added the registry so it's rendering the same image URL as the bitnami chart dependency.
See mariadb documentation here: https://artifacthub.io/packages/helm/bitnami/mariadb/10.4.5#mariadb-common-parameters
Fixes cases where MariaDB image used is hosted in a registry different than docker.io. Also renders the same image value as the bitnami chart.
N/A
N/A
N/A

Add Missing Registry to MariaDB InitContainer

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/metrics-service.yaml
charts/nextcloud/templates/metrics-servicemonitor.yaml
charts/nextcloud/values.yaml

This allows to deploy a Prometheus Operator ServiceMonitor for the metrics scraping.
`prometheus.io/scrape` and `prometheus.io/port` are not really used anymore and instead of manually creating a ServiceMonitor this chart should allow to create the ServiceMonitor
none that I am aware off
none

Allow to deploy a Prometheus Operator ServiceMonitor

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/_helpers.tpl
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

@tvories  this uses AppVersion if the tag key is unset and the tag key if set. I also added a flavor key which allows users to switch to a different image type (e.g. nginx or something else).

Use .Chart.AppVersion for image tag

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/serviceaccount.yaml
charts/nextcloud/values.yaml

Signed-off-by: Mikael Hammarin <mhammarin@ecit.com>
Adding the possibility to annotate the created service account
Would allow more use-cases when automating setup of a new nextcloud instance.
For instance, in GKE this allow automated setup of workload identity.
NA
NA
NA

Support annotations on serviceaccount

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/cronjob.yaml

This fixes #263
cronjobs are no longer broken for those who don't override the cronjob image and tag
You can only override the cronjob image by setting both a repository and a tag for it. Used to be that the tag defaulted to the Nextcloud image tag if you only set a repository (but I'm not sure if that's a sane default)
- fixes #263 
- n/a

Fix "cronjob has no tag"

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml

Init containers were not working when PG or mariaDB is enabled. No way to use `extraInitContainers` if `maria.enabled: true`.
Init containers are now working when PG or mariaDB is enabled.
N/A
- fixes #

extraInitContainers with Maria/PSQL

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/service.yaml

Signed-off-by: Mikael Hammarin <mhammarin@ecit.com>
This fix make it possible to run multiple helm instances in the same namespace without traffic accidently being sent to all of them (service selector is not unique per instance). 
This allow multiple parallel instances of Nextcloud to be run in a single namespace without colliding.
This change make it impossible to lunch multiple deployments which will receive traffic from the same ingress.
However, I can't think of a reason why it would be intended behavior for multiple deployment to use the same service selector.
NA
NA

Fix issue with service selector when running multiple instances

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

Signed-off-by: Mikael Hammarin <mhammarin@ecit.com>
Support to add extra sidecars. A common pattern is to use sidecars to handle local log files so they are handled by cluster-level logging. For Nextcloud, this means handling of nextcloud.log and audit.log files.
In GKE and similar managed kubernetes it would be possible to output nextcloud.log and audit.log so it is handled with Google Logging and Monitoring.
NA
NA
NA

Support for extra sidecars

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/_helpers.tpl

The previous fix at #298 was not correct: the extraVolumeMounts was added in the middle of the previous if. In addition the `-` before `toYaml` is bad.
working extraVolumeMounts
NA
- fixes #296

fix if for extraVolumeMounts

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/metrics-deployment.yaml
charts/nextcloud/values.yaml

- Updates default metrics exporter image tag from `0.5.1` to `0.6.0`
- Adds `metrics.tlsSkipVerify` to values.yaml and README.md (this is a boolean, and defaults to **false**)
- Adds `NEXTCLOUD_TLS_SKIP_VERIFY` env variable to metrics exporter deployment template
This environment variable is described here [xperimental/nextcloud-exporter#environment-variables](https://github.com/xperimental/nextcloud-exporter#environment-variables) with:
> Skip certificate verification of Nextcloud server.
Without this, if you have https set, and you do not have a valid SSL cert,  you will get this error in the pod logs:
```log
level=error msg="Error during scrape: Get \"https://nextcloud.yourdomain.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json\": x509: certificate signed by unknown authority" …
```

Add metrics.tlsSkipVerify and update default metrics exporter image tag to 0.6.0

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

Allows users to set the securityContext for the NextCloud pod, NextCloud container, nginx container, and the cronjob.
Based on #117 by @nlaille.
Allows users to set the securityContext for the NextCloud pod, NextCloud container, nginx container, and the cronjob.
Users can overwrite the default `runAs` property.
- fixes #186
- fixes #252

Add security context for the cronjob, main container, main pod, and ngnix container

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/values.yaml

This is just documenting already present and working features:
- Adds a commented option for both mariadb and postgresql for existingClaim
- Updates README.md with same options
Prevent people from having to cross-reference multiple charts' READMEs.
Think we're good to update the readme and comments without any drawbacks :)
- fixes #281 
Don't think we need to update the Chart Version for this, but updating the chart version next time there's a change to the actual code, will update the `values.yaml` that outputs when you do `helm show values nextcloud/nextcloud`. In the meantime, it's just a couple of comments, so a minor chart version doesn't even seem necessary.

Add documentation for `primary.persistence.existingClaim` for mariadb and postgresql

---

.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/issue.md
.github/workflows/lint-test.yaml
CODE_OF_CONDUCT.md
README.md

- Add issue templates for enhancement vs issue
- Update README.md to link to issues, discussions, and code of conduct
- Add [Code of Conduct from nextcloud/docker](https://github.com/nextcloud/docker/blob/master/CODE_OF_CONDUCT.md)
- update the PR checks to not run on updates to issue/PR templates or code of conduct.
This make it so that we don't have to ping back and ask for more info like `values.yaml` or what version of helm they are running, so that we can get better data to help troubleshoot what's wrong, and collaborate faster on fixes together.
Right now I was hesitant to call the general issue template "bug" template, because we don't really know everything is a bug immediately, but we need a general issue template that still kinda covers bugs. I'm still open to discussion on a …

Create issue templates and link to code of conduct

---

charts/nextcloud/Chart.yaml
charts/nextcloud/values.yaml

The values indicated in the comments are not what the chart actually uses as defaults.
First-time users looking through `values.yaml` know how to configure the secrets correctly.
None I can think of
none
none
I don’t think these are necessary, since this change only affects documentation:

document correct defaults for existingSecret credentials keys

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/_helpers.tpl
charts/nextcloud/templates/deployment.yaml

Fix #306 :
- extraVolumeMounts missing from deployment, was removed when moving mount to the helper template
- wrong indent on extraInitContainers
Fix
None?
- fixes #306

Fix #306 (extraVolumeMounts missing from deployment, wrong indent on extraInitContainers)

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml

Add `extraVolumeMounts` to nginx container. `extraVolumes` are already applied to the container, just the mount is missing.
Lets you add extra volumes to nginx container.
Mounting volumes you might not want on the webserver?!
- fixes #

Fix: extraVolumeMounts for Nginx Container

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml

v3.5.2 of this Helm chart fails to install or upgrade if `nextcloud.extraVolumeMounts` has a value and `nginx.enabled=true`.
This will fix Helm upgrades
N/A
- fixes #357

fix: Unexpected mapping value error with `nextcloud.extraVolumeMounts` and `nginx.enabled`

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/nginx-config.yaml

The [latest Nextcloud documentation](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html) suggests setting `X-Robots-Tag` to `noindex, nofollow`. This changes the nginx configuration to align with that recommendation.
More context: https://github.com/nextcloud/server/issues/37357
Specifically, this explanation: https://github.com/nextcloud/server/issues/37357#issuecomment-1481235495
Prior to this change, someone who is following the Nextcloud documentation to set up their instance may set their nginx reverse proxy to add the `X-Robots-Tag: noindex, nofollow` header. Then their Nextcloud instance still generates the following warning even though they followed the documentation:
> The "X-Robots-Tag" HTTP header is not set to "noindex, nofollow". This is a potential …

Match X-Robots-Tag recommendation in Nextcloud docs

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/values.yaml

Adding `exsitingSecret` parameters for MariaDB, PostgreSQL, and Redis.
Also updating docs to:
-  make it easier to link to sections of the configuration by separating out:
- database config params
- added new exsitingSecret params for both mariadb/postgres
- persistence config params
- metrics config params
- add redis existingSecret params
- update supported versions of k8s (we can't support 1.10-1.19 as they are [not even in support by k8s anymore](https://kubernetes.io/releases/))
- update/add links to bitnami helm charts (they use main instead of master branch now)
Gives README a much needed face lift to make it easier to find stuff. Allows people to use existing secrets by default for all our services.
🤷 
- closes #350

Update docs to have sections and add existingSecret for mariadb, postgresql, and redis

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml

This updates the `helm/chart-releaser-action` in our github workflow from `v1.4.1` to `v1.5`. I've also dropped the patch versions, so that we can always make sure we have patch releases up to date, and then we can still be strict when it comes to minor and major releases.
Keeps our workflows up to date, for security reasons and potential deprecations.
- fixes #329 
Didn't update chart version, because it shouldn't need to be for the github workflow updates

Update helm/chart-releaser-action `v1.4.1` -> `v1.5`; relax requirements for patch versions

---

.github/dependabot.yml

Add docker to package ecosystems that dependabot supports
Should work on helm charts as per the note in [this section of the docs at the bottom](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem):
> [1] Dependabot can update Docker image tags in Kubernetes manifests. Add an entry to the Docker package-ecosystem element of your dependabot.yml file for each directory containing a Kubernetes manifest which references Docker image tags. Kubernetes manifests can be Kubernetes Deployment YAML files or Helm charts. For information about configuring your dependabot.yml file for docker, see "package-ecosystem" in "[Configuration options for the dependabot.yml …

add docker package ecosystem to dependabot

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml

Fixed because:
- helm/kind-action does not create tags for minor versions with no patch version:
https://github.com/helm/kind-action/tags
- helm/chart-testing-action does not create tags for minor versions with no patch version:
https://github.com/helm/chart-testing-action/tags
- helm/chart-releaser does not create tags for minor versions without patch version, so we can't relax this right now:
https://github.com/helm/chart-releaser-action/tags
Looks like this is due to the helm org not releasing tags like `v1.5`, instead of only `v1.5.0`, unlike the [azure/setup-helm github action](https://github.com/Azure/setup-helm/tags), which _does_ tag for minor versions like `v3.5`.
Also bumped kind action version from `1.4` -> `1.5`.
Fixes the issues shown …

Fix helm GitHub Actions version constraints and bump to latest

---

charts/nextcloud/Chart.yaml
charts/nextcloud/values.yaml

Updates default commented out security context values in values.yaml from `"33"` to `33`, and adds more description to comments.
Helps uses not get an error if they just uncomment the defaults for `*.securityContext`
🤷

update security context values from string to int64

---

charts/nextcloud/Chart.yaml
charts/nextcloud/values.yaml

Update well-known webfinger and nodeinfo redirects to match documentation in https://docs.nextcloud.com/server/23/admin_manual/issues/general_troubleshooting.html#service-discovery
People just uncommenting the snippet will now have correct webfinger config, and no warnings in the nextcloud settings.
None that I can see
#240 
...

update ingress snippet comment in values.yaml

---

.github/workflows/release.yaml

Updates default release branch from `master` to `main`
Makes the repo more accessible and keeps us in line with industry standards as listed out in #340.
May be good to wait until we update the official default branch from master to main, so that there is not any confusion. may also be good to hold off on this specific change if we end up using a tag based release method, as it would just introduce more commits that may be confusing to track.
- fixes #340 
I've prepped this PR to make it easier to move forward after getting a maintainer to update the branch name, but it will remain in draft until #339 and #321 are resolved.

update release branch from master to main

---

.github/workflows/lint-test.yaml

set-output commands are deprecated so it's giving us [warnings](https://github.com/nextcloud/helm/actions/runs/4780495468) in the GHA logs:
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
I've updated those commands we were using to the recommendations from the [helm/chart-testing-action example](https://github.com/helm/chart-testing-action#example-workflow).
Removes warnings in the log.
None that I can see here.
none

Update Run chart-testing (list-changed) GHA step to use $GITHUB_OUTPUT

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/templates/service.yaml
charts/nextcloud/values.yaml

Reworked this PR to include other changes from two other PRs to move along these changes faster in bulk.
- Sets default port for `nextcloud.containerPort` to be `80` in values.yaml.
- Changes the service `targetPort` for the nextcloud service to be the `nextcloud.containerPort`.
- Changes all `http` ports in the deployment template to use `nextcloud.containerPort` instead (includes probes)
allows users to set a custom container port like `9000` and have it be referenced in the service.
unsure, open to suggestion
- fixes #384

Set default for nextcloud.containerPort in values.yaml and update YAML templates to use it everywhere

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml

CI fails because of the new self-hosted runners. This forces the jobs to run on the runners provided by Github in order to restore working CI. Failure can be seen in https://github.com/nextcloud/helm/pull/407.
CI works again.
Still depends on Github runners so we might have to still wait longer (but it should be still less than before).

Force CI to run on runners provided by Github

---

charts/nextcloud/Chart.yaml

Update to 27.0.0

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/nginx-config.yaml

Signed-off-by: Mike Kao (github@thetall.gent)
Missing rewrite in default nginx config breaks LDAP. Adding that rewrite in that exists in other installation methods.
Enables LDAP to work correctly in NC25
None
- fixes #213 
https://github.com/nextcloud/server/issues/35594

Fix for #213 missing rewrite in default nginx.conf breaks LDAP

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/metrics-servicemonitor.yaml

This Pull Request should utilize the Helm Release Namespace as a target for the `ServiceMonitor` this Helmchart is optionally deploying.
The metrics actually show up in Prometheus.
I don't see any.
- fixes #312 
None

ServiceMonitor: Specify monitored namespace

---

.github/workflows/release.yaml

So I took a peek at the way [argorproj/argo-helm](https://github.com/argoproj/argo-helm/blob/047ba6b24df9977ec773ca5cf0f00a70565e5c06/.github/workflows/publish.yml#L57-L60) does their releases and it looks like we can just pass in a config file like they've done [here](https://github.com/argoproj/argo-helm/blob/main/.github/configs/cr.yaml).
This _should_ auto-generate release notes going forward!
not sure
- fixes #250

add auto generated release notes

---

.github/workflows/release.yaml

Removes the [softprops/turnstyle](https://github.com/softprops/turnstyle) GitHub Action, and replaces it with the now built in [`concurrency`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) feature for GitHub Workflows.
- Uses the built in feature of GitHub Workflows, which will always wait based on the name of the concurrency group you set, so even if two PRs were merged at the same time, one action would still need to wait for the other.
- One less dependency to keep track of, and in particular turnstyle is using a [deprecated version of nodejs](https://github.com/softprops/turnstyle/blob/ca99add00ff0c9cbc697d22631d2992f377e5bd5/action.yml#L8) that will soon be phased out by GitHub.
- This removes the "The `set-output` command is …

Add concurrency, remove softprops/turnstyle action for Release Charts workflow

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/_helpers.tpl
charts/nextcloud/values.yaml

Hi everyone, thanks for maintaining this useful Helm chart!
I'm using the [DB operator](https://github.com/kloeckner-i/db-operator/blob/master/docs/creatingdatabases.md) to automatically provision databases within my cluster.
It works very similar to Cert-Manager: you create a `Database` CR (instead of a `Certificate` CR) and the operator generates a Secret that contains the connection details for the database, like this:
```yaml
apiVersion: v1
kind: Secret
metadata:
labels:
created-by: db-operator
name: nextcloud-db-credentials
type: Opaque
data:
DB: << base64 encoded database name (generated by db operator) >>
PASSWORD: << base64 encoded password (generated by db operator) >>
USER: << base64 encoded user name (generated by db operator) >>
HOST: << base64 encoded hostname (generated by …
```

Set DB name and host via external secret

---

charts/nextcloud/README.md

- Adds occ command examples - a frequently asked question
- Clean up readme tables - resized to fit data (thanks [dhruvasagar/vim-table-mode](https://github.com/dhruvasagar/vim-table-mode))
- Clean up branding of "nextcloud" to "Nextcloud"
- change supported k8s version - ticks up to the [oldest support k8s release](https://kubernetes.io/releases/)
- adds a table of contents because we have a lot of sections now :D (thanks [mzlogin/vim-markdown-toc](https://github.com/mzlogin/vim-markdown-toc))
Just helps make the readme a bit more presentable and also adds another tidbit of info for those looking to run occ commands.
🤷 I'm open to feedback
for the occ part:
https://github.com/nextcloud/helm/issues/45
it's also come up in two discussions:
https://github.com/nextcloud/helm/discussions/301 …

README updates: Add occ command examples; Clean up readme tables; Clean up branding; change supported k8s version

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md

Updates the default image tag to `27.0.1`
latest stable version as of yesterday
Still no upgrade guide. This'll be the first time I'm upgrading a production instance, so happy to write up a guide on it. Is it just setting `nextcloud.update` to `1`? 🤔 Does that enable the auto-updater? Right now I have it set to the default, `0` and when I go to https://cloud.mydomain.com/updater/ it gives a 404, so maybe that's why? If I set it to `1` before upgrading the helm chart version, and just run a `helm upgrade` with the new values.yaml, will that break anything? I'll obviously take backups before this, but it would be nice to have a section of the README for this as upgrades are a common question we get in the issues.

Update nextcloud app version to `27.0.1`

---

charts/nextcloud/Chart.lock
charts/nextcloud/Chart.yaml

- Upgrades all bitnami subcharts to the latest major versions at time of commit:
- Postgresql appVersion will be bumped from [`14.4.x`](https://github.com/bitnami/charts/blob/b722e860bbb104d308457b49702bc22ff04b6cc1/bitnami/postgresql/Chart.yaml) to [`15.3.0`](https://github.com/bitnami/charts/blob/f985538a832c556241bdc9d90cc7e6eb2c3686df/bitnami/postgresql/Chart.yaml#L8)
- MariaDB appVersion will be bumped from [`10.6.x`](https://github.com/bitnami/charts/blob/fb42c688539128bf5f295595bcd053072e28b1b6/bitnami/mariadb/Chart.yaml#L4) to [`10.11.4`](https://github.com/bitnami/charts/blob/f985538a832c556241bdc9d90cc7e6eb2c3686df/bitnami/mariadb/Chart.yaml#L8C13-L8C20)
- Redis appVersion will be bumped from [`6.2.x`](https://github.com/bitnami/charts/blob/fd2e02ba9c51b8043636055fbb129861461ab9f …

Upgrade Redis, Postgresql, and Maridb to latest OCI Bitnami helm chart versions

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/service.yaml
charts/nextcloud/values.yaml

This PR sets the `.Values.service.loadBalancerIP` field as optional, and does not define it in the service if it's not set in the values.
This is because some `LoadBalancer` implementations allow or even require this value to remain unset, and while it may sometimes be fine to leave it set but blank, this could have unexpected impacts depending on your cluster configuration.
In particular, `MetalLB` will leave the service `<pending>` if the `loadBalancerIP` is set to `nil`, and hardcoding it to a value in the values breaks the ability for `MetalLB`'s IPAM tooling to be used for dynamic address allocation. I suspect other LoadBalancer implementations may have similar behaviors.
The primary benefit is more flexible usage with more `LoadBalancer` implementations.
None I can think of, however …

Do not define loadBalancerIP on service unless set in values

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/_helpers.tpl
charts/nextcloud/templates/secrets.yaml
charts/nextcloud/values.yaml

Adds SMTP hostname as one of the keys in an existing secret you can specify.
You can now set: `nextcloud.existingSecret.smtpHost`
Example values.yaml:
```yaml
nextcloud:
existingSecret:
enabled: true
smtpUsernameKey: smtpUser
smtpPasswordKey:  smtpPassword
smtpHostKey: smtpHostname
```
now you can keep your smtp hostname private and secure, allowing you to open source more of your values.yaml 
none that I can think of
- fixes #431

add ability to pull an SMTP hostname from an existing kubernetes secret

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/metrics-deployment.yaml

As stated out by @millaguie, the NEXTCLOUD_SERVER variable of [metrics-deployment](https://github.com/nextcloud/helm/blob/b35eaa38a721542d7ce73d07e123aa0574244c26/charts/nextcloud/templates/metrics-deployment.yaml#L53) should point to the Nextcloud Service name. But that gets its name from the template function `nextcloud.fullname` and not `.Values.nextcloud.host`. 
Also the port was not contained, that both is changed now.
`metrics-exporter`is now able to reach the Nextcloud Service correctly
- fixes [#279](https://github.com/nextcloud/helm/issues/279)

fix(metrics-deployment): use service name and port

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/nginx-config.yaml
charts/nextcloud/templates/service.yaml
charts/nextcloud/values.yaml

replaces #440 
as the old PR got stuck in git fanciness, simply resubmit as a new PR.
Seems to be the easiest way

 adopt netxcloud.containerport in FPM deployment, allow rootless nginx - nd2 try

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/_helpers.tpl

`REDIS_HOST_PASSWORD` is only set when Redis authentication is turned on.
Because of the container's entrypoint, Redis setup without authentication only works when the environment variable  `REDIS_HOST_PASSWORD` is not set at all (cf. https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh#L122). Previously, the chart only allowed for setting it as an empty string which is not enough and leads to a broken Redis connection string.
None I could think of.

Only set REDIS_HOST_PASSWORD when Redis auth is enabled

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/config.yaml

This allows for the usage of the default redis.config.php when disabling Redis authentication. When redis.auth is disabled, the line with 'password' is not included.
No need to use a custom redis.config.php.
-
-

Don't set redis pw when redis auth is disabled

---

.github/workflows/release.yaml

Accidentally kicked off a release when I added the contributing doc, so this should stop that from happening the future.
This changes `paths-ignore` to just `paths` and then the path is anything under the charts dir.
If there's a change to ONLY the README in the charts dir, it would still attempt a release and fail, but I think the best thing to do longer term is make the README autogenerated via something like [helm-docs](https://github.com/norwoodj/helm-docs) and move all the other docs currently in the charts/nextcloud/README to the root level readme, but this is also going to be fairly rare, so I'm up for debate :)
none
we could also just add CONTRIBUTING.md and CODE_OF_CONDUCT.md to the paths-ignore. Happy to do that instead :)

Update release.yaml - only run release on charts directory changes

---

charts/nextcloud/Chart.lock
charts/nextcloud/Chart.yaml

This PR updates the `postgresql` dependency from `12.11.2` to `12.12.10` as requested by [this comment](https://github.com/nextcloud/helm/pull/446#issuecomment-1798677453). Notably, it doesn't update to `13.2.5`, as major version PostgreSQL updates tend to require manual intervention, and this would require the chart to be bumped to `5.x`.
This update includes various upstream changes to the `postgresql` dependency.
This is not the latest version available. However, as described above, updating to `13.x` would require a major version increase.
N/A
**Steps to test** (copied from #​446; using minikube):
- Start a fresh cluster:\
`minikube start -p nextcloud`
- Clone this PR's branch:
```
mkdir nextcloud-helm && cd nextcloud-helm && git init \
&& git pull --depth=1 …
```

Update bitnami/postgresql to 12.12.10

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/_helpers.tpl
charts/nextcloud/templates/config.yaml
charts/nextcloud/templates/db-secret.yaml
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/templates/metrics-deployment.yaml
charts/nextcloud/values.yaml

- replace indent with nindent (and spaces)
- array of yaml indent
- with+if replace with with (with is already an if)
- nginx if over all probes
- use more with
- default "just" in `values.yaml`
readable code
none
none

chore: lint all templates to fix indentation and update style

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/config.yaml
charts/nextcloud/templates/deployment.yaml

Fixes:
- "remove everthing before <?php":
- https://github.com/nextcloud/helm/pull/465#issuecomment-1817669544
- https://github.com/nextcloud/helm/issues/475
- indent of extraVolumes: https://github.com/nextcloud/helm/issues/475#issuecomment-1817884236
- inside of `with` using `.Values` (e.g. podLabels)

fix: after #465 (remove before <?php, indent of extraVolumes and podLabels)

---

charts/nextcloud/README.md

Adds information on how to enable logging and retrieve those logs, as well as a reminder to anonymize
Ability to point to this section in the README in our issue template as well as in any other issues when users would like to know how to get more detailed logs. Saves typing :)
None that I can think of
- fixes #443 
Don't think there's anything extra

Logging documentation update (#443)

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml

Fix postgresql-isready image
- fixes #468

Fix postgresql-isready image

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml

This just adds some docs for `mariadb.image` and adds a fallback for the image.registry parameter.
This just makes postgres and mariadb a bit more consistent and adds docs
we can't reasonably maintain the image tag in the docs, because it would change everytime we update the subcharts, so I've left it blank.
This fixes the issue brought up in https://github.com/nextcloud/helm/pull/471#issuecomment-1848316834

add mariadb image.registry fallback to docker.io and update docs for mariadb.image parameters

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/metrics-deployment.yaml

use FQDN to access nextcloud server from metrics server
avoid an error message, where metrics was not able to reach NC-server
🤷
- fixes #

metrics use svc.cluster.local to reach nc-server

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md

We remove an indent in the README.md so it matches the values file and the reference in the corresponding helm template file.
The README.md matches the code.
In general one could argue that having `resources:` outside of the `nextcloud:`-Block in the values is not consistent with other components of the deployment, but for the sake of compatibility fixing the README seems to be appropriate.
- fixes #489

fix #489 resources indent in README

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/templates/ingress.yaml
charts/nextcloud/templates/metrics/deployment.yaml
charts/nextcloud/templates/metrics/service.yaml
charts/nextcloud/templates/nextcloud-data-pvc.yaml
charts/nextcloud/templates/nextcloud-pvc.yaml
charts/nextcloud/templates/nginx-config.yaml
charts/nextcloud/templates/php-config.yaml
charts/nextcloud/templates/rbac.yaml
charts/nextcloud/templates/service.yaml

array with:
```yaml
array:
- 3
```
instatt of
```yaml
array:
- 3
```
+ 
this is just of templating part `{{-` will remove all spaces before that, so moved to level of yaml structure.
(i change of `{{` to `{{-` will happen in another PR with the replace of `if` to `when`).
draft, i am waiting for the merge of #516

easy readible indent

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/nginx-config.yaml

added missing MIME type.
Ensure all apps work and remove warning in instance check
N/A
- fixes #519

fix: added missing mime type

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/templates/hpa.yaml
charts/nextcloud/templates/ingress.yaml
charts/nextcloud/templates/metrics/deployment.yaml
charts/nextcloud/templates/metrics/service.yaml
charts/nextcloud/templates/metrics/servicemonitor.yaml
charts/nextcloud/templates/nextcloud-data-pvc.yaml
charts/nextcloud/templates/nextcloud-pvc.yaml
charts/nextcloud/templates/secrets.yaml
charts/nextcloud/templates/service.yaml
charts/nextcloud/templates/serviceaccount.yaml

chore: replace if with with (and improve strip using with -)

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/metrics/servicemonitor.yaml
charts/nextcloud/values.yaml

updated from #349
for this Commit exists already some review in # #481

feat: add namespaceSelector on serviceMonitor

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/configmap-hooks.yaml
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

first step or prepare to #466 
thanks for this hint @jessebot 
https://github.com/nextcloud/helm/issues/466#issuecomment-1857616753
not needed to create a own secret and complex mount per extraVolumes needed to setup such hooks like in:
https://github.com/nextcloud/docker#auto-configuration-via-hook-folders
descripted

feat: add hook scripts to pod

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/configmap-hooks.yaml

a bug in #525 after change from secret to configmap

fix(hooks): configmap does not need base64 encoding

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/nginx-config.yaml

Made the nginx regex also catch the `_arm64` for the code server

Added support for Built-in CODE Server (ARM64)

---

charts/nextcloud/Chart.yaml

Updates nextcloud docker image tag to default to `28.0.4`
latest docker tag
none that I can think of
none that I'm aware of

Update nextcloud appVersion to 28.0.4

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/secrets.yaml

When metrics are not enabled, the use of randAlphaNum was causing constant diffs for nextcloud-token in ArgoCD. To mitigate this issue, now nextcloud-token won't be configured when metrics are not enabled.
This change prevents unnecessary diffs in ArgoCD when metrics are not enabled, leading to a cleaner deployment process.
None
- fixes #<issue_number>
None

chore: Prevent displaying constant diffs for nextcloud-token in ArgoCD

---

.github/workflows/lint-test.yaml

Only run the chart linting action for:
- `charts/nextcloud/Chart.yaml`
- `charts/nextcloud/values.yaml`
- `charts/nextcloud/templates/**` (everything in the templates directory)
This is better than trying to manually exclude all the possible things we don't want to run it on.
Can't think of any.
This would fix the issue where this PR, https://github.com/nextcloud/helm/pull/574, is trying to run the chart linter 🤦

only run chart linting for specific files instead of trying to catch every exception

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

Add the `nginx.extraEnv` parameter allowing to pass environment variables to the Nginx container. 
This is for example useful to set the timezone of the Nginx container through  *TZ* environment variable  (cf #494 and https://github.com/nginxinc/docker-nginx/issues/149).
None, the new parameter is optional.
- fixes #494

Allow to set environment variables to Nginx container

---

.github/workflows/lint-test.yaml
charts/nextcloud/Chart.lock
charts/nextcloud/Chart.yaml

- Updates postgresql chart from `12.12.10` to `15.5.0`
- Updates mariadb chart from `12.2.9` to `18.2.0`
- Updates redis chart from `17.13.*` to `19.5.0`
- Adds a new job to test postgresql installs
As always, you need to check the official upgrade instructions from both bitnami and the upstream providers. Please see the following docs before attempting the nextcloud helm chart upgrade:
- https://github.com/bitnami/charts/tree/main/bitnami/postgresql#to-1300
- https://github.com/bitnami/charts/tree/main/bitnami/mariadb#to-1400
- https://github.com/bitnami/charts/tree/main/bitnami/redis#to-1800
We were pretty out of date on all our subcharts, and this also grants us an end to end test with postgresql, which we've been missing for a while.
- I don't have a test for mysql, only because I …

Update Postgresql, MariaDB, and Redis subcharts to the latest (⚠️ Major updates)

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/metrics/deployment.yaml
charts/nextcloud/values.yaml

This is an update to the `metrics` section of the values.yaml. This PR covers:
- adds *optionally* setting `NEXTCLOUD_SERVER` via the `metrics.server` parameter, instead of allowing the chart to template it out from the k8s service. If not provided, we still use the service name
- adds setting `NEXTCLOUD_INFO_APPS` via the `metrics.info.apps` parameter, which "Enables gathering of apps-related metrics". Defaults to false as it does in the actual container.
- adds `metrics.replicaCount` to the README, as it was missing
- formats the tables in the README (because my linter did it by default 😅 )
This allows users to get more granular when playing with the metrics exporter container.
none that I can see immediately. open to chatting as usual :)
not sure we have any issues on this yet?
See …

Add setting of NEXTCLOUD_SERVER and NEXTCLOUD_INFO_APPS for metrics exporter and clean up docs

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/values.yaml

Added Redis persistent volume settings to values and the readme. This is only to make users aware of how to change these settings, the PR itself doesn't contain any changes to the functioning of the chart.
It will make people aware of how to change the persistent volume settings for Redis.
Too many settings in values might "clutter" the values file and readme.
- fixes #546
not applicable

Add: Redis persistent volumes settings to values

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/service.yaml
charts/nextcloud/values.yaml

Adding Service Type Annotations
Adding Service Type Annotations
None
- fixes https://github.com/nextcloud/helm/issues/185
Updated Readme

Chart update adding Service Annotations ie for LB Use, Issue #185

---

.github/pull_request_template.md

This removes the top header of "Pull Request" and adds a link to the CONTRIBUTING docs into the template.
We already know it's a pull request, so we don't need the extra text. This will allow users to get familiar with our contributing docs, which provide further info on allowing edits by maintainers, for instance.
None that I can think of, but happy to chat about it. This is a low priority PR.

Update pull_request_template.md - remove top header + add link to contributing docs

---

charts/nextcloud/README.md

Add docs on changing php.ini values. Also regenerates the table of contents "Quick Links".
This may otherwise be hard to find in our values.yaml or giant parameters config tables, so with a quick link, maybe others can more quickly access this info.
none that I can think of, but happy to take feedback :)
- fixes #582

add documentation section on adjusting php.ini values

---

.github/workflows/lint-test.yaml

- updates the test jobs to be generated from a `strategy.matrix`
- adds job to matrix to run a test of chart with `nginx.enabled=true` and `image.flavor=fpm` both set
- adds job to matrix to run a test of chart with `hpa.enabled=true` set
- New tests are easier to add :)
- Now if anyone would like to change a config file or other template that seems like it could affect users that use the `nginx.enabled` parameter, this PR will do the bare minimum testing for that.
None that I can think of, but I'm also open to feedback :)
Not sure if we have any issues related to this 🤔 This is just something we've talked about several times.

Refactor lint-test.yaml GHA Workflow to use a matrix for test job generation; Add `nginx.enabled` and `hpa.enabled` tests

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

The change allowes to configure dnsOptions on all nextcloud pods
In some Clusters this option needs to be set. For example k3s clusters can have problems running alpine images.
None

Add possibility to configure custom `dnsConfig` on the Nextcloud pod

---

.github/workflows/lint-test.yaml
charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml

- Sets`spec.replicas` in Nextcloud Deployment _only if_ `hpa.enabled` in values.yaml is set to `false`.
- update hpa ci test to use `hpa.minPods=2`
This _should_ unbreak the environments that use `hpa.enabled` in their values.yaml that also use Argo CD?
None that I can think of after #598 was merged! Open to discussion on this one as always :)
- fixes #561

only set `spec.replicas` in Nextcloud Deployment if `.Values.hpa.enabled` is set to `false`

---

.github/tests/minio_test_values.yaml
.github/tests/test_upload_job.yaml
.github/workflows/lint-test.yaml
charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/files/defaultConfigs/autoconfig.php.tpl
charts/nextcloud/files/defaultConfigs/redis.config.php.tpl
charts/nextcloud/files/defaultConfigs/reverse-proxy.config.php.tpl
charts/nextcloud/files/defaultConfigs/s3.config.php.tpl
charts/nextcloud/files/defaultConfigs/smtp.config.php.tpl
charts/nextcloud/files/defaultConfigs/swift.config.php.tpl
charts/nextcloud/files/defaultConfigs/upgrade-disable-web.config.php.tpl
charts/nextcloud/templates/_helpers.tpl
charts/nextcloud/values.yaml

- Updates the following files to match the upstream [`nextcloud/docker` config files](https://github.com/nextcloud/docker/tree/2accbecd979916d0c0f63fcb97d87f4970616db9/.config):
- `charts/nextcloud/files/defaultConfigs/autoconfig.php.tpl`
- `charts/nextcloud/files/defaultConfigs/redis.config.php.tpl`
- `charts/nextcloud/files/defaultConfigs/reverse-proxy.config.php.tpl` 🆕 
- `charts/nextcloud/files/defaultConfigs/s3.config.php.tpl` 🆕 
- `charts/nextcloud/files/defaultConfigs/smtp.config.php.tpl`
- `charts/nextcloud/files/defaultConfigs/swift.config.php.tpl` 🆕 
- `charts/nextcloud/files/defaultConfigs/upgrade-disable-web.config.php.tpl` 🆕 
- Adds `nextcloud.objectStore.s3` to use [S3 for primary storage](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/primary_stora …

Sync config files from nextcloud/docker repo; Add S3/Swift object storage config; Add S3 ci test; Add `nextcloud.trustedDomains`

---

charts/nextcloud/README.md

Add a dedicated section for Liveness, Readiness, and Startup probes to the README.
We've discussed this a number of times in different issues over the years, but for various reasons, users sometimes need to adjust their probes. This gives us a dedicated link we can use to point our community members to as a good troubleshooting step :)
Also, tinier dedicated table that's easier to clean up.
New section in docs that could throw off other PRs? I'm willing to wait on mine to move others forward though 🙏
There's no one issue specifically, but it was mentioned in https://github.com/nextcloud/helm/issues/584 that I most recently noticed. Will try to add other issues here if/when I find them 🙏
Would have been nice to link here as well: #368
Open to feedback as always :)

Add better liveness/readiness/startup probe docs that we can easily link to

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/metrics/deployment.yaml
charts/nextcloud/values.yaml

Allow users to set the securityContext on both the metrics container and the pod.
More security is good :)
can't think of any, but happy to discuss
- closes #558 as it's virtually the same PR, but with the changes requested in the review as the developer is too busy right now
- partially addresses #356 as it also covers some of this, but the developer is too busy right now
n/a

Add `metrics.securityContext` and `metrics.podSecurityContext`

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/values.yaml

Add `mariadb.global.defaultStorageClass` to our values.yaml and clean up the README to also include `mariadb.primary.persistence.storageClass` and `mariadb.primary.persistence.existingClaim` as they'd be common parameters.
Less confusion about how to use the MariaDB subchart because it better reflects the bitnami helm chart.
none that I can think of, but always happy for feedback :)
- fixes #123
nope

add `mariadb.global.defaultStorageClass` to values.yaml

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/metrics/deployment.yaml
charts/nextcloud/values.yaml

Fix setting `NEXTCLOUD_AUTH_TOKEN` env var for metrics deployment by ensuring we check for `.Values.nextcloud.existingSecret.tokenKey`. Also sets `.Values.nextcloud.existingSecret.tokenKey` to default to `''` which shouldn't be a breaking change, considering it was broken before.
Now users can actually use the `nextcloud.existingSecret.tokenKey` feature.
users will need to remember to set `nextcloud.existingSecret.tokenKey`
- fixes #508 
Fix originally described here:
https://github.com/nextcloud/helm/issues/508#issuecomment-2249855493

fix #508 by checking for `.Values.nextcloud.existingSecret.tokenKey`

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/_helpers.tpl

I did a copypasta typo where I was checking for the s3 bucket parameter instead of the sse c key parameter 🤦 This PR fixes that.
Now SSE C won't be required to use this chart with s3 as a primary object store.
none that come to mind, but happy to chat :)
- fixes #616

fix s3 `secretKeys.sse_c_key` secret key checking typo; now `sse_c_key` is not required for using s3 with this chart

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/values.yaml

Adds a default for `externalDatabase.host` to be `""` so it's clear the type taken, and also reminds people that they need to quote when using a `:` in a value in yaml. Also adds a bit more of a comment for that value and updates the README to reflect both changes.
Just resolves tiny bit of possible confusion around how to specify a database port.
none that I can think of
- fixes #632
- addresses https://github.com/nextcloud/helm/discussions/618

add default of "" for externalDatabase.host; update README to be a little more clear

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/_helpers.tpl

This quotes the `nextcloud.objectStore.s3.legacyAuth` value when rendering it as an env var in `_helpers.tpl`. I think that's why it wasn't working before.
Without this fix, setting the value to true doesn't work.
We could also just have it be this to be more explicit, since the `with` will ignore a value of `false` anyway:
```go
{{- with .Values.nextcloud.objectStore.s3.legacyAuth }}
- name: OBJECTSTORE_S3_LEGACYAUTH
value: "true"
{{- end }}
```
Either should solve the issue 🤷 
- fixes #637

Fix: quote `nextcloud.objectStore.s3.legacyAuth` value when rendering as env var

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/files/nginx.config.tpl
charts/nextcloud/values.yaml

Add an option to configure the listening IP address for the nginx container.
This will allow setting the IP to a value like "[::]" for IPv6 deployments. The current generated configs force the address to 0.0.0.0
None that I can think of. The default value is 0.0.0.0 which is equivalent to the configuration generated by the chart at the moment.
- fixes #636

feat(nginx): add ipFamilies option for IPv4 and IPv6

---

charts/nextcloud/README.md

Update docs a bit more around huge pages to mention other web servers outside of apache.
Previously, the docs were focused on apache, leading some to think that this couldn't affect fpm. Thanks to the good users of #644, we now know it can affect all images, and update the docs to be more clear.
unsure, but open to chatting as always :)
- fixes #644

Update README.md - update bus error info under huge pages documentation

---

charts/nextcloud/README.md

This change documents the value field `nextcloud.postgreSqlInitContainer.securityContext` in the README.
The value gets increased visibility to users, so they know it exists.
More docs to maintain.
- fixes #645
Manually maintaining such a large table of values seems very tedious and error prone. I would recommend looking into a tool to automate it, for example [Bitnami's README generator](https://github.com/bitnami/readme-generator-for-helm).

docs: Add postgreSqlInitContainer values to README

---

.github/workflows/lint-test.yaml
charts/nextcloud/Chart.yaml
charts/nextcloud/test-values/hpa.yaml
charts/nextcloud/test-values/nginx.yaml
charts/nextcloud/test-values/postgresql.yaml
charts/nextcloud/test-values/s3-as-primary-storage.yaml

better overview of values in test
same setup tested in #622

fix(nextcloud): move ci lint-test values to yaml file

---

.github/workflows/lint-test.yaml
charts/nextcloud/Chart.lock
charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/values.yaml

- Add a dependency to the 1.1.20 collabora chart from their official repository
- Add the subchart config to values.yaml
- Add the configuration options documentation to README
- Install collabora as a subchart of nextcloud via helm
- People may try to enable it without knowing what is is and how to configure it (mainly `extra_params`, `server_name`, `aliasgroups` and `annotations`.
- fixes #611 
Tested on my local kubernetes cluster with a HTTPS nginx ingress. Nextcloud can communicate with Collabora. Not tested with HAProxy (though it is only a change in annotations specific to HAProxy).

Feature: Add Collabora as a subchart #611

---

.github/workflows/release.yaml

Add the collabora online helm repo to the release process
Now we can release with collabora online.
Not sure if it should be named collabora or collabora-online
Fixes https://github.com/nextcloud/helm/pull/623#issuecomment-2544026430
none that I can think of, but always happy to chat :)

Update release.yaml - add collabora online helm repo

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md

Hi there! I found this small typo in the docs.

docs: fix typo in s3 config
