charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/templates/hpa.yaml
charts/nextcloud/templates/ingress.yaml
charts/nextcloud/templates/nextcloud-pvc.yaml
charts/nextcloud/templates/service.yaml

Signed-off-by: TJ Wesolowski <wojoinc@pm.me>
Closes #22 
This should be bugfix only, so did not bump minor version.
To test on existing deployed release, delete the `nextcloud` deployment and run a `helm upgrade`.
Confirmed this fix addresses the issue.

[Bugfix] Add component label to application-related resources

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/NOTES.txt
ct.yaml

… repo.
Signed-off-by: Niranjan <newninja18@gmail.com>

Update Notes to show updated version of messages. Update stable chart repo 

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md

I ran into trouble with deploying nextcloud due to hugepages on my nodes. Adding some docs about my findings to hopefully help the next person that has hugepages on their node.
Fixes #32

Adding readme information about hugepages

---

.github/workflows/release.yaml

This is related to https://helm.sh/blog/new-location-stable-incubator-charts/

fix helm stable repo

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

As discussed in #26  I added the startupProbe (default: false) and adjusted the liveness and readiness probes.

Add StartupProbe

---

.github/workflows/lint-test.yaml

Adding `paths-ignore` to `lint-test.yaml` to exclude README.md and LICENSE changes

[meta] Added paths-ignore for README.md and LICENSE

---

.github/pull_request_template.md

[meta] Add pr template

---

.github/workflows/release.yaml

Fixes release workflow to ignore pushes to master when updating README.md or LICENSE

[meta] Adding paths-ignore to release workflow

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/config.yaml
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

Remove the tableprefix option
This is getting deprecated in NC20 - https://github.com/nextcloud/server/pull/21112
It will continue to work for the foreseeable future on existing installs, but maybe we should warn users who have it set that it's being silently ignored?
- fixes #

Remove tableprefix option

---

.github/workflows/lint-test.yaml
.gitignore
charts/nextcloud/Chart.yaml
charts/nextcloud/values.yaml

This updates the PostgreSQL dependency to chart v10.3.7.
Updates the Bitnami chart to the current supported version.
Since it is a major version bump between v9 and v10 of that chart, some values *may* have changed. The Bitnami README [states](https://github.com/bitnami/charts/tree/master/bitnami/postgresql#breaking-changes) the following:
> The term master has been replaced with primary and slave with readReplicas throughout the chart. Role names have changed from master and slave to primary and read.
N/A
I have also updated the Github Actions used in the workflows to their current versions, to make the CI pass.

Update PostgreSQL dependency

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/NOTES.txt

update wrong label value in notes

---

charts/nextcloud/README.md

Added some info on clustering and its dependency on a shared persistence.

document hpa dependency

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml
ct.yaml

This updates workflows to the latest released github actions.
Updated workflows with less bugs
Here might be dragons.

.github: Update workflows

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml
charts/nextcloud/Chart.yaml
charts/nextcloud/values.yaml

https://github.com/xperimental/nextcloud-exporter/compare/v0.3.0...v0.4.0
-
-
-

Update nextcloud-exporter to 0.4.0

---

charts/nextcloud/Chart.lock
charts/nextcloud/Chart.yaml
charts/nextcloud/values.yaml

This updates the nextcloud image to nextcloud 21 and dependency charts to its latest version.
- fixes #

Update to nextcloud 21 and dependency charts

---

charts/nextcloud/Chart.lock
charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/values.yaml

* Update image version to 22.2.3
* Sync charts
* Fix a missed update in README.md
- fixes #

nextcloud: Update to 22.2.3

---

charts/nextcloud/Chart.yaml
charts/nextcloud/values.yaml

This variable will be used in https://github.com/nextcloud/helm/blob/master/charts/nextcloud/templates/deployment.yaml#L12

mention deploymentAnnotations in values.yaml

---

charts/nextcloud/Chart.yaml
charts/nextcloud/values.yaml

...as this variable will be used here https://github.com/nextcloud/helm/blob/master/charts/nextcloud/templates/deployment.yaml#L30

mentioned podAnnotations in values.yaml

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/_helpers.tpl

Reverts nextcloud/helm#171
Reverts incorrect change to kubernetes semver check

Revert "Use networking.k8s.io/v1 Ingress above k8s v1.19"

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/cronjob.yaml

use stable api version for batch jobs
chart is ready for k8s v1.25+
none, its backward compatible

use apiVersion: batch/v1 if available

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/metrics-deployment.yaml
charts/nextcloud/templates/secrets.yaml
charts/nextcloud/values.yaml

Updates to 0.5.0 and adds support for token auth.
For full automation of token auth see also: https://github.com/nextcloud/docker/pull/1656

Update nextcloud-exporter to 0.5.0

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/cronjob.yaml

Fixes issue preventing installation of Helm chart on K8s v1.20 clusters
Allows Helm chart to be deployed on K8s v1.20 clusters
None known
- fixes #209

Fixes issue with batch/v1/CronJob detection

---

charts/nextcloud/Chart.lock
charts/nextcloud/Chart.yaml

Update chart dependencies to latest minor release.

Bump chart dependencies

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/templates/deployment.yaml
charts/nextcloud/values.yaml

Support for initContainers
To allow customized bootstraping of Nextcloud, ex add static apps to the main container.
None
NA
NA

support for initContainers

---

charts/nextcloud/Chart.lock
charts/nextcloud/Chart.yaml

Bumps to nextcloud 24.0.2
Updates Dependencies 
- [] (optional) Variables are documented in the README.md

Bump to 24.0.2 / update dependencies

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/_helpers.tpl
charts/nextcloud/values.yaml

replaces https://github.com/nextcloud/helm/pull/237
- fixes #

bump to nextcloud 24.0.3

---

charts/nextcloud/Chart.yaml

bump to 24.0.5

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/deployment.yaml

Signed-off-by: Kenny Retzlaff <kenny.retzlaff@gmail.com>
Depending on the value of cronjob.enabled the cron sidecar container is created.
- fixes #297

Respect cronjob.enabled setting

---

charts/nextcloud/Chart.lock
charts/nextcloud/Chart.yaml

Update to 25.0.1
Latest NC release
Tested this on my installation, worked flawless.

Update to 25.0.1

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/_helpers.tpl

Fixes #296 
extraVolumeMounts working again.
NA
- fixes #296 
NA

extraVolumeMounts working again

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/metrics-deployment.yaml

The new introduction of env variable, breaks the deployment
this is a helmchart bug fix

Bug: Fix issue cause by boolean without quotes into env variable

---

charts/nextcloud/Chart.yaml

Update to 25.0.3

---

charts/nextcloud/Chart.yaml

Update to 25.0.4

---

README.md

docs: Link to README.md changed

---

charts/nextcloud/Chart.yaml

Update to 26.0.0

---

charts/nextcloud/Chart.yaml

Accidentally merged a downgrade of the app version when resolving a merge conflict through the web interface on my last PR. See here: https://github.com/nextcloud/helm/commit/e37c3cc0c40545177d702be2b987d6c2c5e6facc
I apologize for my mistake.
Fix regression.
shouldn't be any. if anything the last merge was a drawback.

Fix app version regression

---

charts/nextcloud/Chart.yaml

Latest NC version
@jessebot shouldn't dependabot have caught this? Maybe it isn't configured correctly?

Update to 26.0.1

---

charts/nextcloud/Chart.yaml

Upgrade to 26.0.2

---

charts/nextcloud/README.md

Uses sh instead of bash so the examples work in alpine based containers as well. Got introduced in https://github.com/nextcloud/helm/pull/419

Use sh instead of bash as container shell in examples

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md

Clarify the chart documentation for Nextcloud cron jobs. This was also proposed in PR #404 but it was abandonned, so this is a second attempt. Some parts have been reused in this PR.
Configuration of cron jobs will be clearer for users.
The existing parameter have not been updated for backward compatility issue, so `cronjob` parameter name could still be misleading, but it is acceptable I think.
N/A
- parameters description has been updated
- CronJob wording has been removed 
- sidecar container behavior explained
- unnecessary manual configuration explained

Cron jobs documentation update

---

README.md

Just notes on the root level readme that this is a community maintained helm chart to reduce confusion

Update README.md - note that this chart is maintained by the community

---

charts/nextcloud/Chart.yaml

Update to 27.1.1

---

charts/nextcloud/Chart.yaml

Update to the latest Nextcloud version.
Getting the features and fixes done in latest Nextcloud version.
None.

Update to 27.1.2

---

charts/nextcloud/Chart.yaml

Updates Nextcloud to the latest version.
Users get the latest fixes and improvements.

Update to 27.1.3

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md

Documentation update to close out issue #236  
Clearer documentation to avoid a frequent trip-up with users when filling in the values.yaml file
Slightly wordier documentation
- fixes #236 
Opted to put this clarifying note in just the README and not the values file itself to avoid clutter. If someone is confused about what to put in the username, or having issues, they will naturally check the README, where this should then help them.
- [X ] DCO has been [signed off on the commit](https://docs.github.com/en/github/authenticating-to-github/signing-commits).
- [ X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ X] (optional) Variables are documented in the README.md

Smtp documentation update

---

charts/nextcloud/Chart.yaml

Updates Nextcloud to the latest version.
Users get the latest fixes and improvements.

Update to 27.1.4

---

CONTRIBUTING.md
README.md

This add some more items to the contributing docs to check before submitting a PR, and it now briefly goes over testing the changes locally.
Users can learn about `helm lint`, `helm template`, and the `ct` (chart testing) command. These are all tools by the helm project itself.
more to read :P
n/a
n/a

Update CONTRIBUTING.md - add testing tips and screenshot for allow edits by maintainers

---

charts/nextcloud/Chart.yaml

Updates Nextcloud to the latest version.
Users get the latest fixes and improvements.

Update to 28.0.0

---

charts/nextcloud/Chart.yaml

Updates Nextcloud to the latest version.
Users get the latest fixes and improvements.

Update to 28.0.1

---

charts/nextcloud/Chart.yaml
charts/nextcloud/templates/metrics/deployment.yaml

i make a mistake in #517 
sorry @provokateurin

fix(metrics): indent in deployment

---

charts/nextcloud/Chart.yaml

Update to 28.0.3

---

charts/nextcloud/Chart.yaml

Update to the latest version of Nextcloud.
Get the latest fixes.

feat: update appVersion to 29.0.1

---

charts/nextcloud/Chart.yaml

update: 29.0.2

---

charts/nextcloud/Chart.yaml

update: 29.0.3

---

charts/nextcloud/Chart.yaml

update: 29.0.4

---

charts/nextcloud/Chart.yaml

update: 29.0.6

---

charts/nextcloud/Chart.yaml

Take latest version in use. Chart major version changed because of the updated major version of Nextcloud.
There may be bugs and / or regressions.

update: 30.0.0

---

charts/nextcloud/Chart.yaml

Take latest version in use. Chart major version changed because of the updated major version of Nextcloud.
There may be bugs and / or regressions.

update: 30.0.1

---

charts/nextcloud/Chart.yaml

Take latest version in use.
There may be bugs and / or regressions.

update: 30.0.2

---

charts/nextcloud/Chart.yaml

Take latest version in use.
There may be bugs and / or regressions.

update: 30.0.3

---

charts/nextcloud/Chart.yaml
charts/nextcloud/README.md
charts/nextcloud/values.yaml

This just adds some more comments to the collabora chart values, sets the actual defaults of the chart, and updates the README to include those defaults. Also updates the README table of contents.
Now our values match the upstream chart, the docs are clearer, and this will hopefully release properly.
Not sure, but always open to chat!
n/a

add collabora comments and update README to include collabora section

---

charts/nextcloud/Chart.yaml

update: 30.0.5

---

charts/nextcloud/Chart.yaml

fix(nextcloud): update version to 30.0.6

---

charts/nextcloud/Chart.yaml

fix(nextcloud): bump to version v31.0.9
